# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Inside the mind of Sean
email: seanf215@gmail.com
description: >
  Just the musings of a developer looking to make sense of his code.
  Any advice within here is given without warrenty of correctness or best practice.
  Take it for what it is worth.
baseurl: ""
url: "https://sfairchild.github.io/"
twitter_username: LogicSean
github_username:  sfairchild

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
exclude: [vendor]
